var cards = [
  {name: "Acetate", formula: "C<sub>2</sub>H<sub>3</sub>O<sub>2</sub><sup>-</sup>"},
  {name: "Ammonium", formula: "NH<sub>4</sub><sup>+</sup>"},
  {name: "Arsenate", formula: "AsO<sub>4</sub><sup>3-</sup>"},
  {name: "Arsenite", formula: "AsO<sub>3</sub><sup>3-</sup>"},
  {name: "Azide", formula: "N<sub>3</sub><sup>-</sup>"},
  {name: "Benzoate", formula: "C<sub>7</sub>H<sub>5</sub>O<sub>2</sub><sup>-</sup>"},
  {name: "Borate", formula: "BO<sub>3</sub><sup>3-</sup>"},
  {name: "Bromate", formula: "BrO<sub>3</sub><sup>-</sup>"},
  {name: "Carbonate", formula: "CO<sub>3</sub><sup>2-</sup>"},
  {name: "Chlorate", formula: "ClO<sub>3</sub><sup>-</sup>"},
  {name: "Chlorite", formula: "ClO<sub>2</sub><sup>-</sup>"},
  {name: "Chromate", formula: "CrO<sub>4</sub><sup>2-</sup>"},
  {name: "Cyanide", formula: "CN<sup>-</sup>"},
  {name: "Dichromate", formula: "Cr<sub>2</sub>O<sub>7</sub><sup>2-</sup>"},
  {name: "Dihydrogen phosphate", formula: "H<sub>2</sub>PO<sub>4</sub><sup>-</sup>"},
  {name: "Dihydrogen phosphite", formula: "H<sub>2</sub>PO<sub>3</sub><sup>-</sup>"},
  {name: "Hydrogen carbonate", formula: "HCO<sub>3</sub><sup>-</sup>"},
  {name: "Hydrogen phosphate", formula: "HPO<sub>4</sub><sup>2-</sup>"},
  {name: "Hydrogen phosphite", formula: "HPO<sub>3</sub><sup>2-</sup>"},
  {name: "Hydrogen sulfate", formula: "HSO<sub>4</sub><sup>-</sup>"},
  {name: "Hydrogen sulfide", formula: "HS<sup>-</sup>"},
  {name: "Hydrogen sulfite", formula: "HSO<sub>3</sub><sup>-</sup>"},
  {name: "Hydroxide", formula: "OH<sup>-</sup>"},
  {name: "Hypochlorite", formula: "ClO<sup>-</sup>"},
  {name: "Iodate", formula: "IO<sub>3</sub><sup>-</sup>"},
  {name: "Manganate", formula: "MnO<sub>4</sub><sup>2-</sup>"},
  {name: "Nitrate", formula: "NO<sub>3</sub><sup>-</sup>"},
  {name: "Nitrite", formula: "NO<sub>2</sub><sup>-</sup>"},
  {name: "Oxalate", formula: "C<sub>2</sub>O<sub>4</sub><sup>2-</sup>"},
  {name: "Perchlorate", formula: "ClO<sub>4</sub><sup>-</sup>"},
  {name: "Permanganate", formula: "MnO<sub>4</sub><sup>-</sup>"},
  {name: "Peroxide", formula: "O<sub>2</sub><sup>2-</sup>"},
  {name: "Phosphate", formula: "PO<sub>4</sub><sup>3-</sup>"},
  {name: "Phosphite", formula: "PO<sub>3</sub><sup>3-</sup>"},
  {name: "Silicate", formula: "SiO<sub>3</sub><sup>2-</sup>"},
  {name: "Sulfate", formula: "SO<sub>4</sub><sup>2-</sup>"},
  {name: "Sulfite", formula: "SO<sub>3</sub><sup>2-</sup>"},
  {name: "Tartrate", formula: "C<sub>4</sub>H<sub>4</sub>O<sub>6</sub><sup>2-</sup>"},
  {name: "Thiocyanate", formula: "SCN<sup>-</sup>"},
  {name: "Thiosulfate", formula: "S<sub>2</sub>O<sub>3</sub><sup>2-</sup>"}
]

//  {name: "", formula: ""}, <sub></sub>
